### ISSUE TITLE
init complains chalk has no attribute 'format_cyan'

### ISSUE THREAD

**Issue by binblee** [alibaba/derrick#19]
(derrick) demo $ derrick init
Detecting Java version ...
? What's your image repo   demo
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/Users/user/.virtualenvs/derrick/lib/python2.7/site-packages/derrick/core/logger.py", line 21, in format
    return fmt.format(record)
  File "/Users/user/.virtualenvs/derrick/lib/python2.7/site-packages/derrick/core/logger.py", line 34, in format
    _chalk = get_chalk_color(level)
  File "/Users/user/.virtualenvs/derrick/lib/python2.7/site-packages/derrick/core/logger.py", line 52, in get_chalk_color
    _chalk = chalk.format_cyan
AttributeError: 'module' object has no attribute 'format_cyan'
Logged from file logger.py, line 79

**Comment by binblee** [comment]
from pip list I got pychalk (2.0.0) which means 2.0 is installed instead of pychalk 1.1.0 from requirements.

**Comment by navneet-arya** [comment]
yaa that's right
